# Usign the Clean Blog theme

title: Paris Ellis Unit
author: ellis-paris
email: gabriel.peyre@ens.fr
description: Paris Ellis Unit
baseurl: ""
url: "https://ellis-paris.github.io/"
github_username:  ellis-paris

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: ellis-paris
gems:
  - jekyll-feed
  - jekyll-paginate
