# Usign the Clean Blog theme

title: Data@PSL
author: data-psl
email: gabriel.peyre@ens.fr
description: Data@PSL Program
baseurl: ""
url: "https://data-psl.github.io/"
github_username:  data-psl

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Data@PSL
gems:
  - jekyll-feed
  - jekyll-paginate
